<?php if(array_key_exists('import_url', $config)) : ?>
<link href="<?=$config['import_url']?>" rel="stylesheet">
<?php endif ?>
<style type="text/css">
  @font-face {
    /*******************************************************/
    /* ********* Sortir le code dur dans style.css *********/
    /*******************************************************/
    /*test 1*/
    /*font-family: "script-mt-bold";
    src: url("fonts/SCRIPTBL.TTF");*/

    /*test 2*/
    /*font-family: "brush-script-mt-bold";*/
    /*src: url("fonts/BRUSHSCI.TTF");*/

    /*test config*/
    /*font-family: <?=$config['font-family'] ?>;*/
  }
  html,body{
    /*font-family: <?=$config['font-family'] ?>;*/
    font-size: <?=$config['font-size_body'] ?>vh;
    background-color: #<?=$config['background-color'] ?>;
    color: #<?=$config['color'] ?>;
  };
  header li a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }
  header li a:hover, header li a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }
  a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }
  a:hover{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }
  a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }
  h2{
    font-size: <?=$config['font-size_h2'] ?>vh;
  }
  #navPC li{
    font-size: <?=$config['font-size_body'] ?>vh;
  }
  .pagination a{
    color: #<?=$config['color'] ?>;
  }
  .flexslider{
    background-color: #<?=$config['flexslider_background-color'] ?>;
  }
  .formStyle fieldset{
    background-color: #<?=$config['form_background-color'] ?>;
  }
  /******************* ecran scrollmagic ************************/






/*  #containerAdresse{
    
  }*/

/*  #containerSoins{
    width: 60%;
    height: 500px;
    margin: 0 auto;
    padding-top: 17%;
    text-align: center;
  }
  #containerSoins div{
    margin: 5% 2% 0% 2%;
  }*/

 
/*
  #autre:hover > h4{
    opacity: 1;
  }
  #soins:hover >  h4{
    opacity: 1;
  }
  #uv:hover > h4{
    opacity: 1;
  }
  #tarif:hover > h4{
    opacity: 1;
  }
  #maquillage:hover > h4{
    opacity: 1;
  }
  #minceur:hover > h4{
    opacity: 1;
  }
*/

  /* certainement du ménage à faire ici */
  #containerAccueil li a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }
  #containerAccueil li a:hover, #containerAccueil li a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }

  #menuBas li a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }

  #menuBas li a:hover, #menuBas li a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }

.activeMenu a{
  color: #<?=$config['couleur_lien_actif'] ?> !important;
}
  
</style>