<?php if(array_key_exists('import_url', $config)) : ?>;
<link href="<?=$config['import_url']?>" rel="stylesheet">
<?php endif?>

<style type="text/css">
  html,body{
    /*font-family: "script-mt-bold", serif;*/
    /*font-family: "brush-script-mt-bold", serif;*/
    font-family: <?=$config['font-family'] ?>;
    width: 100%;
    height:100%;
    background-color: #<?=$config['background-color'] ?>;
    font-size: 2.2vh;
    color: #<?=$config['color'] ?>;
  };
  
  <?php /* if(array_key_exists('import_url', $config)) : ?>;
  @import url("<?=$config['import_url']?>");
  <?php endif */?>

  @font-face {
    /*test 1*/
    /*font-family: "script-mt-bold";*/
    /*src: url("fonts/SCRIPTBL.TTF");*/

    /*test 2*/
    /*font-family: "brush-script-mt-bold";*/
    /*src: url("fonts/BRUSHSCI.TTF");*/

    /*test config*/
    font-family: <?=$config['font-family'] ?>;

  }


  a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }

  a:hover{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }

  a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }
  /* certainement du ménage à faire ici */
  #containerAccueil li a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }
  #containerAccueil li a:hover, #containerAccueil li a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }

  #menuBas li a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }

  #menuBas li a:hover, #menuBas li a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }

  header li a{
    color: #<?=$config['couleur_lien'] ?>;
    text-decoration: none;
  }

  header li a:hover, header li a:focus{
    color: #<?=$config['couleur_lien_actif'] ?>;
  }

</style>