<?php include('header_admin.phtml') ?>
<?php 
// var_dump($valeurs_tableau_form);
// var_dump($erreurs_champs_form);
// var_dump($oArticles);
?>
<h2><?= $action_txt ?> un article</h2>

<?php if($erreur) : ?>
<div class="alert alert-danger" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <?= $erreur ?>
</div>
<?php endif ?>

<?php if(in_array($_GET['action'], ['del','mod'])) :?>
<div class="well">
    <h3><?= $article['titre'] ?></h3>
    <p>Postée par <?= $article['auteur'] ?> le <?= $article['date'] ?></p>
    <p><img src="../img/thumb/<?= $article['image'] ?>" alt="<?= $article['titre'] ?>"/></p>
    <p><?= $article['texte'] ?></p>
</div>
<?php endif ?>

<form method="post" enctype="multipart/form-data">
<?php if($_GET['action'] =='del') : ?>
    <div class="well">
        <h3>Voulez-vous réellement supprimer l'article "<?= $article['titre'] ?>" ?</h3>
    </div>    
    <!-- formulaire suprression -->
    <input type="hidden" name="id" value="<?= $article['id'] ?>" />
   
<?php else : ?>
    <!-- formulaire ajout / édition -->
    <div class="form-group<?=isset($erreurs_champs_form['titre']) ? ' has-error' : '' ?>">
        <label for="id_titre" class="control-label">Titre :</label>
        <input type="text" id="id_titre" name="titre" class="form-control" value="<?= $valeurs_tableau_form['titre'] ?>" />
        <?php if(isset($erreurs_champs_form['titre'])) { ?>
        <p class="help-block">
        <?= $erreurs_champs_form['titre'] ?>
        </p>
        <?php } ?>
    </div>

    <?php if($_SESSION['droit'] <=2) : ?>
    <div class="form-group<?=isset($erreurs_champs_form['auteur']) ? ' has-error' : '' ?>">
        <label for="id_auteur" class="control-label">Auteur :</label> 
        <select id="id_auteur" name="auteur">
            <?php foreach ($oUser->getListAll() as $user) : 
                $selected = ($valeurs_tableau_form['auteur'] == $user['nom']) ? ' selected=selected ' : '' ?> 
                <?php if($user['droit'] >= $_SESSION['droit']) : ?>
                <option value="<?= $user['id']?>" <?= $selected ?>/><?= $user['nom']?></option>
                <?php endif ?>
            <?php endforeach ?>
        </select>
    </div>            
    <?php else : ?>
        <input type="hidden" name="auteur" value="<?= $_SESSION['id']?>" />
    <?php endif ?>            

    <div class="form-group<?=isset($erreurs_champs_form['section']) ? ' has-error' : '' ?>">
        <label for="id_section" class="control-label">Section : </label> 
        <select id="id_section" name="section">
            <?php foreach ($oSections->getListHasItem() as $section) : 
                $selected = ($valeurs_tableau_form['section'] == $section['id']) ? ' selected=selected ' : '' ?> 
                <option value="<?= $section['id']?>" <?= $selected ?>/><?= $section['nom']?></option>
            <?php endforeach ?>
        </select>
    </div>    

    <div class="form-group<?=isset($erreurs_champs_form['texte']) ? ' has-error' : '' ?>">
        <label for="id_texte" class="control-label">Texte :</label>
        <textarea id="id_texte" name="texte" class="form-control"><?= $valeurs_tableau_form['texte'] ?></textarea>
        <?php if(isset($erreurs_champs_form['texte'])) { ?>
        <p class="help-block">
        <?= $erreurs_champs_form['texte'] ?>
        </p>
        <?php } ?>
    </div>

    <div class="form-group<?=isset($erreurs_champs_form['image']) ? ' has-error' : '' ?>">
        <label for="id_image" class="control-label">Image :</label>
        <input type="file" id="id_image" name="image" />
        <?php if(isset($erreurs_champs_form['image'])) { ?>
        <p class="help-block">
        <?= $erreurs_champs_form['image'] ?>
        </p>
        <?php } ?>
    </div>

    <?php if($_SESSION['droit'] <=2) : ?>
    <div class="form-group">
        <label class="control-label">Mettre en ligne? </label>
        <label class="radio-inline">
            <input type="radio" name="visible" id="inlineRadio1" value="1" <?=($valeurs_tableau_form['visible']) ? '  checked' : '' ?>> Oui
        </label>
        <label class="radio-inline">
            <input type="radio" name="visible" id="inlineRadio2" value="0" <?= !($valeurs_tableau_form['visible']) ? '  checked' : '' ?>> Non
        </label>            
    </div>
    <?php else : ?>
        <input type="hidden" name="visible" value="0" />      
    <?php endif ?>

<?php endif ?>

    <div class="form-group">
        <input type="submit" value="<?= $action_txt ?>" class="btn btn-primary"/>
        <a href="articles/list/" class="btn btn-default">Annuler</a>
    </div>
</form>


<?php include('footer_admin.phtml'); ?>