<?php
include('header_admin.phtml'); ?>

<h2>Liste des paramètres : <?=$type_config?></h2>
<?php 
if($erreur != ""):
?>
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?= $erreur ?>
</div> 
<?php endif ?>

<?php if(isset($_SESSION['message']) && $_SESSION['message']!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $_SESSION['message'];
        $_SESSION['message'] = '';
        ?>
</div>
<?php endif ;

// echo var_dump($list_configs);
// echo var_dump($_GET);
?>
<?php if($_SESSION['droit'] <=1) : ?>
<p><a href="configs/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Créer une config</a></p>
<?php endif?>

<?php if(!empty($list_configs)) : ?>
<div class="responsive-table-line">
<!-- <table class="table table-striped table-bordered table-hover table-responsive"> -->
<table class="table table-striped table-bordered table-hover table-condensed">
<!-- <table class="table table-striped table-bordered table-hover table-condensed table-body-center"> -->
    <thead>
        <tr>
            <th>Tag</th>
            <th>Valeur</th>
            <th>Description</th>
            <?php if($_SESSION['droit'] <=1) : ?>
            <th>Type</th>
            <th>Accès client?</th>
            <?php endif?>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list_configs as $config) : ?>
        <tr>
            <td data-title="Tag">
                <?= $config['tag']?>
            </td>
            <td data-title="Valeur">
                <?= (strlen($config['valeur']) > 50 )?substr($config['valeur'], 0, 50) . '...' : $config['valeur'] ?>
            </td>
            <td data-title="Description">
                <?php if($config['description'] != ''):?>
                    <?= $config['description']?>
                <?php else : ?>
                    <span class="glyphicon glyphicon-ban-circle" style="color:red"></span>
                <?php endif?>
            </td>

            <?php if($_SESSION['droit'] <=1) : ?>
                <td data-title="Type"><?=$config['type']?></td>
            <?php endif?>
            
            <?php if($_SESSION['droit'] <=1) : ?>
            <td data-title="Accès client?">
                <?php if($config['acces_client']):?>
                    <span class="glyphicon glyphicon-ok-circle" style="color:green"></span>
                <?php else : ?>
                    <span class="glyphicon glyphicon-ban-circle" style="color:red"></span>
                <?php endif?>
            </td>
            <?php endif?>

            <td data-title="Action">
                <?php if($_SESSION['droit'] <=1) : ?>
                <a href="configs/del/<?= $config['id']?>/" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                &nbsp;
                <?php endif?>
                <a href="configs/mod/<?= $config['id']?>/" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
</div>
<?php endif ?>
<?php include('footer_admin.phtml');?>