<?php
include('header_admin.phtml') ?>

<h2>Liste des Contacts</h2>

<?php if(isset($_SESSION['message']) && $_SESSION['message']!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $_SESSION['message'];
        $_SESSION['message'] = '';
        ?>
</div> 
<?php endif ?>
<?php
// echo '<pre>'.var_dump($tab_news).'</pre>';
?>
<div class="responsive-table-line">
<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Email</th>
            <th>Origine</th>
            <th>Téléphone</th>
            <th>Adresse</th>
            <th>Note</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($liste_contacts as $contact) : ?>
        <tr>
            <td data-title="Nom">
                <?= $contact['prenom']?>&nbsp;<?= $contact['nom']?>
            </td>
            <td data-title="Email">
                <?= $contact['mail']?>
            </td>
            <td data-title="Origine">
                <?php 
                switch($contact['type_contact']) {
                    case 'form_contact':
                        echo "Formulaire de contact";
                        break;
                    case 'livreor':
                        echo "Livre d'or";
                        break;
                    case 'client':
                        echo "Client";
                        break;
                }
                ?>
            </td>
            <td data-title="Téléphone">
                <?= $contact['tel']?>
            </td>
            <td data-title="Adresse">
                <?= $contact['adresse']?>&nbsp;<?= $contact['cp']?>&nbsp;<?= $contact['ville']?>
            </td>
            <td data-title="Note">
                <?= $contact['note']?>
            </td>
            <td data-title="Action">
<!--                 <a href="contacts/del/<?= $contact['id']?>/" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                &nbsp; -->
                <a href="contacts/mod/<?= $contact['id']?>/" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
</div>
<?php 

include('footer_admin.phtml');?>