        </div> <!-- fin de la div"main-container" -->
    </main>
        <footer>
            <!-- /!\ => $_SESSION['connected'] à remettre sans ! -->
            <?php if(isset($_SESSION['connected']) && $_SESSION['connected']):?>
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="container">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="logout.php">
                                <span class="glyphicon glyphicon-off"></span>
                                Déconnexion  <?= $_SESSION['login'] ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <?php endif ?>
        </footer>
    </body>
</html>