<?php
include('header_admin.phtml'); ?>
<img id="logoBG" src="../img/logoBG.png">
<h2>Home de l'admin</h2>
<?php 
if($erreur != ""):
?>
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?= $erreur ?>
</div> 
<?php endif ?>

<?php if(isset($_SESSION['message']) && $_SESSION['message']!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $_SESSION['message'];
        $_SESSION['message'] = '';
        ?>
</div> 
<?php endif ?>
<!-- <p><a href="creation.php" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Créer une news</a></p> -->
<!-- <div class="container"> -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
        <p>
        <a href="users/add/" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-user"></span> Créer un compte utilisateur 
        </a>
        </p> 
        </div>

        <div class="col-md-3">
        <p>
        <a href="configs/list/" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-cog"></span> Configurations 
        </a>
        </p> 
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
        <p>
        <a href="sections/add/" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-list-alt"></span> Créer une section 
        </a>
        </p>   
        </div>
    </div> 
</div> 
<?php include('footer_admin.phtml');?>