<?php include('header_admin.phtml') ?>
<?php 
// var_dump($valeurs_tableau_form);
// var_dump($oMessages);
?>
<h2><?= $action_txt ?> un message du livre d'Or</h2>

<?php if($erreur) : ?>
<div class="alert alert-danger" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <?= $erreur ?>
</div>
<?php endif ?>

<form method="post">
<?php if($_GET['action'] =='del') : ?>
    <div class="well">
        <h3>Voulez-vous réellement supprimer le message "<?= $oMessages->fields['text'] ?>" écrit par <?= $oMessages->fields['prenom']?>&nbsp;<?= $oMessages->fields['nom']?> ?</h3>
    </div>    
    <!-- formulaire suprression -->
    <input type="hidden" name="id" value="<?= $oMessages->fields['id'] ?>" />
   
<?php else : ?>

<?php endif ?>

    <div class="form-group">
        <input type="submit" value="<?= $action_txt ?>" class="btn btn-primary"/>
        <a href="livreor/list/" class="btn btn-default">Annuler</a>
    </div>
</form>


<?php include('footer_admin.phtml'); ?>