<?php include('header_admin.phtml') ?>
<?php 
// var_dump($valeurs_tableau_form);
// var_dump($oMessages);
?>
<h2><?= $action_txt ?> un message du livre d'Or</h2>

<?php if($erreur) : ?>
<div class="alert alert-danger" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <?= $erreur ?>
</div>
<?php endif ?>

<form method="post">
<?php if($_GET['action'] =='del') : ?>
    <div class="well">
        <h3>Voulez-vous réellement supprimer le message "<?= $oMessages->fields['text'] ?>" écrit par <?= $oMessages->fields['prenom']?>&nbsp;<?= $oMessages->fields['nom']?> ?</h3>
    </div>    
    <!-- formulaire suprression -->
    <input type="hidden" name="id" value="<?= $oMessages->fields['id'] ?>" />
   
<?php else : ?>
    <!-- formulaire édition -->
    <div class="well">
        <h3>De <?= $oMessages->fields['prenom']?>&nbsp;<?= $oMessages->fields['nom']?> le <?= date("j M Y à H\hi", strtotime($oMessages->fields['date'])) ?></h3>
    </div> 

    <div class="form-group<?=isset($erreurs_champs_form['text']) ? ' has-error' : '' ?>">
        <label for="field_texte">Message : </label>
        <textarea id="field_texte" name="text" class="form-control"><?= $valeurs_tableau_form['text'] ?></textarea>
        <?php if(isset($erreurs_champs_form['text'])) : ?>
          <p style="color:red;"><?= $erreurs_champs_form['text'] ?></p>
        <?php endif ?>     
    </div>

    <div class="form-group">
        <label class="control-label">Publier ? </label>
        <label class="radio-inline">
            <input type="radio" name="visible_livreor" id="inlineRadio1" value="1" <?=($valeurs_tableau_form['visible_livreor']) ? '  checked' : '' ?>> Oui
        </label>
        <label class="radio-inline">
            <input type="radio" name="visible_livreor" id="inlineRadio2" value="0" <?= !($valeurs_tableau_form['visible_livreor']) ? '  checked' : '' ?>> Non
        </label>            
    </div>    

<?php endif ?>

    <div class="form-group">
        <input type="submit" value="<?= $action_txt ?>" class="btn btn-primary"/>
        <a href="livreor/list/" class="btn btn-default">Annuler</a>
    </div>
</form>


<?php include('footer_admin.phtml'); ?>