<?php
include('header_admin.phtml'); ?>

<h2>Liste des message postés dans le livre d'Or</h2>
<?php 
if($erreur != ""):
?>
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?= $erreur ?>
</div> 
<?php endif ?>

<?php if(isset($_SESSION['message']) && $_SESSION['message']!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $_SESSION['message'];
        $_SESSION['message'] = '';
        ?>
</div>
<?php endif ;

// echo '<pre>'.var_dump($list_configs).'</pre>';
?>
<?php if(!empty($list_messages)) : ?>
<div class="responsive-table-line">
<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Date</th>
            <th>Message</th>
            <th>Visible</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list_messages as $message) : ?>
        <tr>
            <td data-title="Nom">
                <?= $message['prenom']?>&nbsp;<?= $message['nom']?>
            </td>
            <td data-title="Date">
                <?= date("j M Y à H\hi", strtotime($message['date'])) ?>
            </td>
            <td data-title="Message">
                <?= substr($message['text'], 0, 50) . '...' ?>
            </td>
            <td data-title="Visible">
                <?php if($message['visible_livreor']):?>
                    <span class="glyphicon glyphicon-ok-circle" style="color:green"></span>
                <?php else : ?>
                    <span class="glyphicon glyphicon-ban-circle" style="color:red"></span>
                <?php endif?>
            </td>             
            <td data-title="Action">
                <a href="livreor/del/<?= $message['id']?>/" class="btn btn-danger"  title="Suppression"><span class="glyphicon glyphicon-trash"></span></a>
                <a href="livreor/mod/<?= $message['id']?>/" class="btn btn-success"title="Editer"><span class="glyphicon glyphicon-pencil"></span></a>                
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
</div>
<?php else : ?>
    <p>Aucun message pour le moment.</p>
<?php endif ?>
<?php include('footer_admin.phtml');?>