<?php
include('header_admin.phtml') ?>

<h2>Liste des logs Users</h2>

<?php
// echo '<pre>'.var_dump($tab_news).'</pre>';
?>
<div class="responsive-table-line">
<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Action</th>
            <th>Date</th>
            <th>IP</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list_logs as $log) : ?>
        <?php if($log['droit'] >= $_SESSION['droit']): ?>
        <tr>
            <td data-title="Nom">
                <?= $log['user_name']?>
            </td>
            <td data-title="Action">
                <?= $log['action']?>
            </td>
            <td data-title="Date">
                <?= $log['date']?>
            </td>
            <td data-title="IP">
                <?= $log['ip']?>
            </td>
        </tr>
        <?php endif ?>
        <?php endforeach ?>
    </tbody>
</table>
</div>
<?php 

include('footer_admin.phtml');?>