<?php
include('header_admin.phtml'); ?>

<h2>Liste des modules activés</h2>
<?php 
if($erreur != ""):
?>
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?= $erreur ?>
</div> 
<?php endif ?>

<?php if(isset($message) && $message!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $message;
        $message = '';
        ?>
</div>
<?php endif ;

// if(count($_POST)) {
//     echo '<pre>'.var_dump($_POST).'</pre>';
// }
//     echo '<pre>'.var_dump($oConfigs).'</pre>';

?>
<form method="post">
    <div class="responsive-table-line">
    <table class="table table-striped table-bordered table-hover table-responsive">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Actif</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($list_modules as $module) : ?>
            <tr>
                <td data-title="Nom">
                    <label for="<?= $module['slug']?>"><?= $module['nom']?></label>
                </td>
                <td data-title="Actif">
                    <input type="checkbox" name="module[]" value="<?= $module['slug']?>" id="<?= $module['slug'] ?>" <?= ($module['actif'])? 'checked ' : '' ?>>
                </td>
                <td data-title="Date">
                    <?= date("j M Y à H\hi", strtotime($module['date'])) ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    </div>
    <div class="form-group">
        <!-- obligé de lui mettre une value, sinon rien dans $_POST à la validation -->
        <input type="submit" value="Mettre à jour" name="Mettre à jour" class="btn btn-primary"/>
    </div>
</form>

<?php include('footer_admin.phtml');?>