<?php
include('header_admin.phtml'); ?>
<?php if($_GET['action'] == 'list') :?>
    <h2>Liste des Tarifs</h2>
<?php else : ?>
    <h2>Liste des groupes de Tarifs</h2>
<?php endif ?>    
<?php 
if($erreur != ""):
?>
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?= $erreur ?>
</div> 
<?php endif ?>

<?php if(isset($_SESSION['message']) && $_SESSION['message']!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $_SESSION['message'];
        $_SESSION['message'] = '';
        ?>
</div>
<?php endif ;

// echo '<pre>'.var_dump($list_tarifs).'</pre>';
// echo '<pre>'.var_dump($_GET).'</pre>';
?>
<p>
    <a href="tarifs/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Créer un tarif</a>
    <a href="tarifs/addtype/" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Créer un groupe de tarifs</a>
</p>
<div class="responsive-table-line">
<table class="table table-striped table-bordered table-hover table-responsive">
    <thead>
        <?php if($_GET['action'] == 'list') :?>
        <tr>
            <th>Nom</th>
            <th>Valeur</th>
            <th>Groupe</th>
            <th>Action</th>
        </tr>
        <?php else : ?>
        <tr>
            <th>Nom</th>
            <th>Action</th>
        </tr>
        <?php endif ?>
    </thead>
    <tbody>
        <?php foreach($list_tarifs as $tarif) : ?>
        <?php if($_GET['action'] == 'list') :?>
        <tr>
            <td data-title="Nom">
                <?= $tarif['prestation']?>
            </td>
            <td data-title="Valeur">
                <?= $tarif['prix']?>
            </td>
            <td data-title="Groupe">
                <?= $tarif['groupe']?>
            </td>
            <td data-title="Action">
                <a href="tarifs/del/<?= $tarif['id']?>/" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                &nbsp;
                <a href="tarifs/mod/<?= $tarif['id']?>/" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
        <?php else : ?>
        <tr>
            <td data-title="Nom">
                <?= $tarif['nom']?>
            </td>
            <td data-title="Action">
                <a href="tarifs/deltype/<?= $tarif['id']?>/" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                &nbsp;
                <a href="tarifs/modtype/<?= $tarif['id']?>/" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>        
        <?php endif ?>
    <?php endforeach ?>
    </tbody>
</table>
</div>
<?php include('footer_admin.phtml');?>