<?php
include('header_admin.phtml') ?>

<h2>Liste des Users</h2>

<?php if(isset($_SESSION['message']) && $_SESSION['message']!= ''): ?>
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
        <?php echo $_SESSION['message'];
        $_SESSION['message'] = '';
        ?>
</div> 
<?php endif ?>
<?php
// echo '<pre>'.var_dump($tab_news).'</pre>';
?>
<p><a href="users/add/" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>Créer un compte</a></p>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Niveau</th>
            <th>Nombre de News</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($liste_users as $user) : ?>
        <!-- seuls les dieux voient les dieux... -->
        <?php if($user['droit'] >= $_SESSION['droit']) : ?>
        <tr>
            <td>
                <?= $user['id']?>
            </td>
            <td>
                <?= $user['nom']?>
            </td>
            <td>
                <?= $user['niveau']?>
            </td>
            <td>
                <!-- si on a la clef correspondant à l id utilisateur, on affiche le nombre de news, 0 sinon (tous les utilisateurs n'ont pas créé de news) -->
                <?= isset($tab_news[$user['id']]) ? $tab_news[$user['id']] : '0'?>
            </td>
            <td>
                <a href="users/del/<?= $user['id']?>/" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                &nbsp;
                <a href="users/mod/<?= $user['id']?>/" class="btn btn-success"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
        <?php endif ?>
        <?php endforeach ?>
    </tbody>
</table>

<?php 

include('footer_admin.phtml');?>