<?php include('header.phtml') ?>
<main>
	<img id="logoBG" src="img/robinetHover.png">
	<!-- <h2 class="titrePage">Contact</h2> -->

     <div id="contactPage">
          <!-- form contact -->
         <?php if($erreur) : ?>
         <span style="color:red;"><?= $erreur ?></span>
         <?php else : ?>
         <?= $message; ?> 
         <?php endif ?>          

          <h3><?= $oSections->fields['texte'] ?></h3>
          <!-- carte -->
          <div id="contactPageMap">
            <iframe src="<?= htmlspecialchars_decode($config['url_google_map'])?>" frameborder="0" allowfullscreen></iframe>            
          </div>

          <!-- infos -->
          <p><?=$config['nom_site']?>
          </br><?=$config['adresse']?> </br> <?=$config['cp']?> <?=$config['ville']?>
          </br><?=$config['tel']?>
          </br>
          </br>
          </br>Nos horaires :
          </br>Lundi : Fermé
          </br>Mardi, Mercredi, Jeudi et Vendredi : 9h00 à 12h00 - 14h00 à 19h00
          </br>Samedi : 10h00 à 14h00 
          </br>Dimanche : Fermé</p>
          </br>

    
        <div class="clear"></div>
        <!-- form contact -->
        <?php
        if($tab_modules['form_contact']) 
             include('form_contact.phtml') 
        ?>

        <div class="clear"></div>

        <?php if($tab_modules['livreor']) : ?>
             <div class="bouton lienItem"><a href="livreor.html">Ecrivez dans le Livre d'Or</a></div>
        <?php endif ?>
    </div>


    <nav id="menuBasSection">
      <?php include('menu.phtml');?>
    </nav>
</main>


<?php include('footer.phtml') ?>