      <div id="containerScreen3">
<!--         <?php foreach ($tabSectionScreen3 as $section) :?>
        <div class="container" id="<?= $section['tag']?>">
          <div class="containerScreen3Nom"><h4><?= $section['nom']?></h4></div>
          <a href="<?= $section['tag']?>.html">
            <img class="image2" src="img/pastille_arbre_hover.png" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <img class="image1" src="img/pastille_arbre.png" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
          </a>
        </div> 
        <?php endforeach ?>
-->

        <div class="container" id="soins">
          <h4>L'Engazonnement</h4>
          <a href="#">
            <img class="image2" src="img/pastille_arbre_hover.png" alt="Les épilations, le maquillage, les manucures de l'institut de beauté">
            <img class="image1" src="img/pastille_arbre.png" alt="Les épilations, le maquillage, les manucures de l'institut de beauté">
          </a>
        </div> 

        <div class="container" id="uv">
          <h4>Clôture et portail</h4>
          <a href="#">
            <img class="image2" src="img/pastille_arbre_hover.png" alt="Les séances uv, cabine uv, bronzage de l'insitut de beauté">
            <img class="image1" src="img/pastille_arbre.png" alt="Les séances uv, cabine uv, bronzage de l'insitut de beauté">
          </a>
        </div> 
<!-- </br> -->
        <div class="container" id="maquillage">
          <h4>Entretien ponctuel</h4>
          <a href="inxex.php#ancreEntretien">
            <img class="image2" src="img/pastille_arbre_hover.png" alt="Le maquillage Sothys, cours de maquillage, maquillage soir et soirées de l'insitut de beauté">
            <img class="image1" src="img/pastille_arbre.png" alt="Le maquillage Sothys, cours de maquillage, maquillage soir et soirées de l'insitut de beauté">
          </a>
        </div> 

        <div class="container" id="minceur">
          <h4>Boiserie d’extérieur</h4>
          <a href="index.php">
            <img class="image2" src="img/pastille_arbre_hover.png" alt="CelluM6, cellu m6, technologie endermolift, minceur, mincir, séance de perte de poids de l'insitut de beauté">
            <img class="image1" src="img/pastille_arbre.png" alt="CelluM6, cellu m6, technologie endermolift, minceur, mincir, séance de perte de poids de l'insitut de beauté">
          </a>
        </div> 

        <div class="container" id="tarif">
          <a href="index.php">
            <img class="image2" src="img/pastille_arbre_hover.png" alt="Les tarifs de l'insitut de beauté">
            <img class="image1" src="img/pastille_arbre.png" alt="Les tarifs de l'insitut de beauté">
          </a>
          <h4>Les tarifs</h4>
        </div> 

      </div>