      <div id="containerScreen3">
         <?php foreach ($tabSectionScreen3 as $section) :?>
        <div class="container" id="<?= $section['tag']?>">
          <!-- <div class="containerScreen3Nom"> --><h4><?= $section['nom']?></h4><!-- </div> -->
          <a href="<?= $section['tag']?>.html">
            <?php if(empty($section['image'])) :?>
            <img class="image2" src="img/pastilleArbreHover3.png" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <img class="image1" src="img/pastilleArbre.png" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <?php else : ?>
            <img class="image2" src="img/section/hover_<?= $section['image']?>" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <img class="image1" src="img/section/<?= $section['image']?>" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <?php endif ?>
          </a>
        </div> 
        <?php endforeach ?>


</div>