      <div id="containerSection">
        <h3><?=$config['txt_screen2']?></h3>

        <div id="sectionsScreen2">
          

        <?php 
        // var_dump($tabSectionScreen2);
        foreach ($tabSectionScreen2 as $section) :?>
          <div class="container" id="<?= $section['tag']?>">
            <a href="<?= $section['tag']?>.html">
              <h3><?= $section['nom']?></h3>
              <?php if(empty($section['image'])) :?>
              <img class="image1" src="img/pastilleArbre.png" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <?php else : ?>
            <img class="image1" src="img/section/<?= $section['image']?>" alt="<?= $section['nom']?> <?=$config['nom_site']?>">
            <?php endif ?>
            </a>
          </div>
        <?php endforeach ?>

        </div>
</div>

