	  <ul class="slides">
	   <?php foreach($newsSection as $key => $news):?>
	    <li>
	      <a href="<?= $oSections->fields['tag'] ?>/<?= $news['id']?>/<?= urlencode(htmlentities($news['titre']))?>">
	      <img src="img/thumb/<?= $news['image'] ?>" alt="<?= $news['titre'] ?>"/>

	      <div class="textFlexslider">
	      	<?php if($nav_en_cours != $news['tagSection']) :?>
		  		<h3><?= $news['nomSection'] ?>:</h3>
		  	<?php endif ?>
		    <h4><?= $news['titre'] ?></h4>
		      <div class="clear"></div>
		       <p><?= substr($news['texte'], 0, 50) ?>
		          ...
		       </p>
	      </div>

	      </a> 
	    </li>
	    <?php endforeach ?>
	  </ul>