<!DOCTYPE html>
<html>
<head>

  <title>
    <?= $oSections->fields['nom'] ?> <?=$config['separateur_menu']?> <?=$config['nom_site']?>
  </title>
  <meta charset="utf-8" />
  <meta http-equiv="Content-Type" content="text/html"/>
  <!-- <base href="/ludh2o/"> -->
  <base href="<?=str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME'])?>">

  <meta name="description" content="<?= $oSections->fields['meta-description'] ?>"/>
  <meta name="keywords" content="<?= $oSections->fields['meta-keywords'] ?>"/>
  
  <link rel="icon" type="image/png" href="img/logoFavicon.png" />
  <link rel="stylesheet" href="css/flexslider.css" type="text/css">
  <link rel="stylesheet" href="fancyBox/jquery.fancybox.css" type="text/css" media="screen" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" ></script> 
  <script src="modules/jQuery.js"></script>
  <script src="modules/jquery.flexslider.js"></script>
  <script type="text/javascript" src="fancyBox/jquery.fancybox.pack.js"></script>
  <!-- <?php include('css/custom_css.phtml') ?> -->
  <link type="text/css" rel="stylesheet" href="css/style.css" />
  <script type="text/javascript" charset="utf-8">
    $(window).load(function() {


//plugin flexslider
      //simple FlexSlider call
      $('.flexslider').flexslider();
      // more complex call
      $('.flexslider').flexslider({
          animation: "slide",
          controlsContainer: ".flex-container",
          start: function(slider) {
            $('.total-slides').text(slider.count);
          },
          after: function(slider) {
          $('.current-slide').text(slider.currentSlide);
          }
      });


  //Menu déroulant
          $(function(){
        $('#btnMenu').on('click touch', function(e){
            $('#navMobile').slideToggle();
            e.preventDefault();
          });
        });


});

</script>
  


</head>

<body>
<header>
     <!--  <a class="btn btn-navbar" id="btnMenu" href="#menuBas">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a> -->
  <nav id="navMobile">
    <?php include('menu.phtml');?>
  </nav>
    <div id="containerAccueilSection">
      <div id="containerHeadSection">
        <div id="containerHeadTxt">
          <a href="home.html">
            <img id="logoHome" src="img/logoH2oSansFond.png" alt="Logo <?=$config['nom_site']?>"/>
          </a>
          <h1 id="h1Home"><?=$config['titre_home']?></h1>
          <h4 id="h4Home"><?=$config['slogan']?></h4>
          <!-- <h5 id="h5Home"><?=$config['sous_titre_home']?></h2> -->
        </div>
    </div>
    <nav id="navPC">
      <?php include('menu.phtml');?>
    </nav>

  <div class="clear"></div>

</header>
