<?php
include('header.phtml');
// var_dump($_GET);
// var_dump($oSections);
// var_dump($oArticles);
// var_dump($tabNombreNewsSection);
?>
<main>
	<?php if($erreur == '') : ?>
	<div class="blog-slide">
	        <h2 class="blog-slide-title"><?= $oArticles->fields['titre']?></h2>
	        <div class="blog-slide-img">
	            <img src="img/thumb/<?= $oArticles->fields['image']?>" alt="">
	        </div>
	        <p class="blog-slide-text"><?= htmlspecialchars_decode($oArticles->fields['texte'])?></p>

		    <?php if(!empty($oArticles->fields['code_video_youtube'])) :?>
		    <p class="blog-slide-text"><iframe width="450" height="315" src="https://www.youtube.com/embed/<?= $oArticles->fields['code_video_youtube'] ?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>
		    <?php endif ?>	        

		    <?php if(!empty($oArticles->fields['url_externe'])) :?>
		    <p class="blog-slide-text"><a href="<?= $oArticles->fields['url_externe'] ?>" title="voir le site <?= $oArticles->fields['url_externe'] ?>" target="_blank">Visitez leur site web</a></p>
		    <?php endif ?>	        

	        <p class="blog-slide-info">
	        Posted on: <?= $oArticles->fields['date']?><br>
	        Posted by: <?= $oArticles->fields['auteur']?><br/>
        	Posted in: <?= $oArticles->fields['section_nom']?><br/>	        
	        </p>
	</div>
	<?php else : ?>
	    <p class="error"><?= $erreur ?></p>
	<?php endif; ?>
	<a href="<?= $oSections->fields['tag']?>.html">Retour à la liste</a>
</main>
<?php
include('footer.phtml'); 
?>