<?php include('header.phtml') ?>
<main>
<br/><br/>
    <h4><?= $oSections->fields['texte'] ?></h4>
    <?php if($erreur) : ?>
    <p style="color:red;"><?= $erreur ?></p>
    <?php else : ?>
    <?= $message; ?> 
    <?php endif ?>
    <br/><br/>
	  <div id="livreOrPage">
         <ul>
           <?php foreach($tab_messages as $msg):?> 
            <li>
              <p>Posté par <span style="color: #<?=$config['couleur_lien_actif'] ?>;"> <?= $msg['prenom'] ?> </span> le <?= date("j M Y à H\hi", strtotime($msg['date'])) ?></p>
              <p><?= $msg['text'] ?></p>
            </li>
          <?php endforeach ?>
          </ul> 
      </div>
     </br>
     <div ><?php echo $menu_pagination; ?></div>
     </br>
     </br>
    <div class="formStyle" <?= !empty($message) ? 'style="display:none"' : '' ?>>
        <h3>Ecrivez dans le livre d'Or:</h3>
<!--        <p class="paragraphePage" style="font-size: 2vh;">Ceci n'est pas un formulaire de contact. C'est un espace publique où chacun(e) partage son avis et/ou son expérience de l'institut. </br>
       Si vous n'avez pas trouver l'information que vous cherchez sur ce site, merci de contacter Anne Boucher, l'esthéticenne, par téléphone au 03 29 25 21 62.</p> -->
       <form method="post">
       <fieldset>
        <label for="field_titre">Nom : </label>
        <input id="field_titre" type='text' name='nom' size='50' maxlength="255" value="<?= $valeurs_tableau_form['nom'] ?>"/>
        <?php if(isset($erreurs_champs_form['nom'])) : ?>
          <p style="color:red;"><?= $erreurs_champs_form['nom'] ?></p>
        <?php endif ?>
        <br/>

        <label for="field_titre">Prénom : </label>
        <input id="field_titre" type='text' name='prenom' size='50' maxlength="255" value="<?= $valeurs_tableau_form['prenom'] ?>"/>
        <?php if(isset($erreurs_champs_form['prenom'])) : ?>
          <p style="color:red;"><?= $erreurs_champs_form['prenom'] ?></p>
        <?php endif ?>      
        <br/>

        <label for="field_titre">E-mail : </label>
        <input id="field_titre" type='email' name='mail' size='50' maxlength="255" value="<?= $valeurs_tableau_form['mail'] ?>"/>
        <?php if(isset($erreurs_champs_form['mail'])) : ?>
          <p style="color:red;"><?= $erreurs_champs_form['mail'] ?></p>
        <?php endif ?>      
        <br/>

        <label for="field_texte">Message : </label>
        <textarea id="field_texte" type='textarea' name='text' size='50' maxlength="255"><?= $valeurs_tableau_form['text'] ?></textarea>
        <?php if(isset($erreurs_champs_form['text'])) : ?>
          <p style="color:red;"><?= $erreurs_champs_form['text'] ?></p>
        <?php endif ?>     
      </fieldset>
      <br/>
      <input id="field_title" type="submit" value="Publier"/>

    </div>

</main>


<?php include('footer.phtml') ?>