      <div class="motifScreen2">
        <div id="containerContact">

          <div id="contactMap">
            <h4>Nous Situer</h4>
            <iframe src="<?= htmlspecialchars_decode($config['url_google_map'])?>" frameborder="0" allowfullscreen>
            </iframe>
            <p><?=$config['adresse']?> <br/> <?=$config['cp']?> <?=$config['ville']?>
            <br/><?=$config['tel']?>
            </p>

            <h5>Nos horaires :</h5>
            <p>
            Lundi : Fermé
            <br/>Mardi, Mercredi, Jeudi et Vendredi : 9h00 à 12h00 - 14h00 à 19h00
            <br/>Samedi : 10h00 à 14h00 
            <br/>Dimanche : Fermé
            </p>
          </div>

          <!-- module livreor -->
          <?php if($tab_modules['livreor']) : ?>
          <div id="livreOr">
            <h4>Livre d'Or</h4>
            <ul>
             <?php foreach($tab_messages as $message):?> 
              <li>
                <p>Posté par <span style="width:50%; color: #c95500;"> <?= $message['prenom'] ?> </span> le <?= date("j M Y à H\hi", strtotime($message['date'])) ?></p>
                <p><?= $message['text'] ?></p>
              </li>
            <?php endforeach ?>
            </ul>          
          </div>
          <?php endif ?>      
          <div class="clear"></div>
            
          <!-- module formulaire de contact -->
          <?php if($tab_modules['form_contact']) : ?>
          <div class="bouton lienLivreOrContact"><a href="contact.html">Formulaire de contact</a></div>
          <?php endif ?>  

          <!-- module livreor -->
          <?php if($tab_modules['livreor']) : ?>
          <div class="bouton lienLivreOrContact"><a href="livreor.html">Ecrivez dans le Livre d'Or</a></div>
          <?php endif ?>      

  <div class="clear"></div>
         
        </div>
         
          <noscript>
            <nav id="menuBas">
              <?php include('menu.phtml');?>          
            </nav>
          </noscript>

            <nav id="menuBas">
              <?php include('menu.phtml');?>
            </nav>
      </div>