      <div class="motifScreen1">
        <div id="containerAccueil">
          <div id="containerHead">
              <div id="containerHeadTxt">
                <img id="logoHome" src="img/logoH2oSansFond.png" alt="Logo <?=$config['nom_site']?>">
                <h1 id="h1Home"><?=$config['titre_home']?></h1>
                <h4 id="h4Home"><?=$config['slogan']?></h4>
                <h5 id="h5Home"><?=$config['sous_titre_home']?></h5>
              </div>
            

          </div>
          <nav id="navPC">
              <?php include('menu.phtml');?>
          </nav>
         
       <?php 
        // echo "<pre>";
        // var_dump($oArticles);
        // var_dump($newsSection);
        // echo "</pre>";
       ?>
        <div class="clear"></div>

        <div class="flexslider fHome"> 
            <?php include('flexslider.phtml');?>
        </div>
        <div class="clear"></div>

        <div class="clear"></div>
        </div>
      </div>