      <div id="containerAccueil">
        <div id="containerHead">
            <!-- <img id="logoHome" src="img/logoNew.png" alt="Logo <?=$config['nom_site']?>"> -->
            <img id="logoHome" src="img/logoH2oSansFond.png" alt="Logo <?=$config['nom_site']?>">
          <h1 id="h1Home">
            <?=$config['titre_home']?>
          </h1>
        </div>
        <div id="containerAdresse">
          <h4><?=$config['slogan']?></h4>
          <!-- <p><?=$config['adresse']?>, <?=$config['cp']?> <?=$config['ville']?><a href="contact.html"> <img src="img/marqueur.png"></a><?=$config['tel']?></p> -->
          <!-- <p><?=$config['tel']?></p> -->
        </div>
        <nav id="navPC">
            <?php include('menu.phtml');?>
        </nav>
       
     <?php 
      // echo "<pre>";
      // var_dump($oArticles);
      // var_dump($newsSection);
      // echo "</pre>";
     ?>
      <div class="clear"></div>

      <div class="flexslider"> 
          <?php include('flexslider.phtml');?>
      </div>
      <div class="clear"></div>

      <div class="clear"></div>
      </div>