<?php
include('header.phtml'); 
// var_dump($oSections);
// var_dump($oArticles);
// var_dump($newsSectionPage);
// var_dump($_SERVER);
?>

<main>

	<!-- <img id="logoBG" src="img/logoBG.png"> -->
	<h2><?= $oSections->fields['nom'] ?></h2>

   <?php if(!empty($newsSection) && count($newsSection) > 1) : ?>
   <h4>Dernières publications</h4>
	<div class="flexslider">
        <?php include('flexslider.phtml');?>
	</div>
    <?php endif ?>
	<div class="clear"></div>

    <?php if($erreur == '') : 
        echo $menu_pagination;
        // affciahge des news de la page correspondante 
        foreach ($newsSectionPage as $key => $news) : ?>
        <div class="blog-slide">
            <div class="blog-slide-img">
                <a href="<?= $oSections->fields['tag'] ?>/<?= $news['id']?>/<?= urlencode($news['titre'])?>" title="lire <?= $news['titre'] ?>">
                    <img src="img/thumb/<?= $news['image']?>" alt="">
                </a>
            </div>
            <a href="<?= $oSections->fields['tag'] ?>/<?= $news['id']?>/<?= urlencode($news['titre'])?>" title="lire <?= $news['titre'] ?>">
             <h2 class="blog-slide-title"><?= $news['titre']?></h2>
            </a>
            <p class="blog-slide-info">
            Posté le <?= $news['date']?> par <?= $news['auteur']?>
            </p>
            <p class="blog-slide-text"><?= htmlspecialchars_decode($news['texte'])?>
                <a href="<?= $oSections->fields['tag'] ?>/<?= $news['id']?>/<?= urlencode($news['titre'])?>" title="lire <?= $news['titre'] ?>">lire plus</a>
            </p>
        </div>
  <?php endforeach ?>

  <?= $menu_pagination ?>
    <?php else : ?>
    <p class="error"><?= $erreur ?></p>
    <?php endif; ?>



    <nav id="menuBasSection">
      <?php include('menu.phtml');?>
    </nav>

</main>
<?php include('footer.phtml') ?>